name: forensodont
description: "The final instantiation of 'Forensodont'."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  url_launcher: ^6.3.1
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  file_picker: ^10.1.9
  http: ^1.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
